@startuml
skinparam wrapWidth 180
actor Happy_Me as "Счастливый Я"

card Environment [
=Место
----
Я живу, в уютном месте, может быть в тёплом климате, с красивым видом на природу.
Вокруг безопасно. Я знаю, что ни со мной, ни с моими близкими ничего не случиться.
----
===Как я пойму что достиг желаемого?
<color:green>На улицах нету пьяных/агрессивных, везде чисто</color>
]

card Girlfriend [
=Девушка
----
Я живу вместе с девушкой. У нас с ней близкие и чувственные отношения, мы любим друг друга.
Если мы ссоримся, то это не на долго и каждая такая ссора только укрепляет наш союз.
Мой партнёр в каждый момент времени уверен, что хочет быть со мной, как и я - в том что хочу быть с ней.
Мы оба любим секс.
Мы ежедневно работаем над укреплением наших отношений.
Всё вышеперечисленное - это <u>осознанный выбор обоих</u>
----
===Как я пойму что достиг желаемого?
<color:green>Наши отношения проверены временем. Мы вместе 2 года и мы всё ещё оба выбираем быть вместе. </color>
]
note bottom
Для того чтобы всё получилось нужно девушку:
* найти
* не проебать
end note

card SelfRealisation [
=Самореализация
----
Я самореализован в обществе. У меня есть дело/проект, которому я посвящаю своё время, я в этом деле профи и мне нравится им заниматься.
Он мой, личный, а не на дядю. Мой проект приносит пользу людям.
----
===Как я пойму что достиг желаемого?
<color:green>Мне постоянно приходит положительная обратная связь. Мне говорят "спасибо", прислушиваются к моему мнению. Моего участия в деятельности желают и приглашают меня как специалиста.</color>
]

card Social [
=Социум
----
Меня окружают друзья, семья, все меня любят и уважают.
----
===Как я пойму что достиг желаемого?
<color:green>Я часто провожу время с друзьями и нам всем от этого хорошо. Меня зовут проводить время снова и снова.</color>
]

card Freedom [
=Свобода
----
Я не испытываю недостатка в деньгах и могу заниматься в жизни чем захочу.
----
===Как я пойму что достиг желаемого?
<color:green>У меня есть пассивный доход, который полностью покрывает мои средние ежемесячные расходы на семью.</color>
]

card InnerFeelings [
=Внутренние ощущуния
----
Я в каждый момент времени понимаю где я нахожусь в своей жизни. Я чётко знаю куда и зачем я иду.
То, чем я занимаюсь - это мой осознанный выбор.
Я уверен в себе и спокоен. Никто и ничто не может меня сломить. Любые неприятности воспринимаются мной как опыт. Всё - опыт, он не может быть негативным.
===Как я пойму что достиг желаемого?
<color:green>Отсутствие ощущения потерянности, никомуненужности???. Я просыпаюсь по утрам с улыбкой, т.к. знаю что сегодня будет ещё один день, в который я сделаю ещё один шажок вперёд.</color>
----
===Непосредственные действия
<color:violet>Строить планы на выходные. Попытаться поймать ощущение "всё идёт по плану", даже если это план - валяться весь день на диване. Любой план должен быть гибким.</color>
]

Happy_Me .-> Environment
Happy_Me .-> Girlfriend
Happy_Me .-> SelfRealisation
Happy_Me .-> Social
Happy_Me .-> Freedom
Happy_Me .-> InnerFeelings

@enduml