name: generate plantuml
#ignoring. Manual plugin trigger cause of svg generation problem
on:
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: |
          ls
          ls docs
      - name: plantuml
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: docs
          message: "Render PlantUML files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}